# Create post:
POST http://localhost:3000/api/post HTTP/1.1
Content-Type: application/json

{
  "title": "Some title of new tech post",
  "announcement": "Some announcement of new tech post",
  "text": "Some text of new tech post",
  "isReposted": false,
  "commentCount": 0,
  "likeCount": 0,
  "userId": "90fea18a-a714-44ba-9503-23f093cefb16",
  "state": "published",
  "type": "text",
  "tags": ["Home", "Work", "Digital", "Technology"]
}

###

# Get all posts:
GET http://localhost:3000/api/post HTTP/1.1
Content-Type: application/json

###

# Get post by ID:
GET http://localhost:3000/api/post/978c05ff-fc3a-4f12-99a4-7474d9a34dce HTTP/1.1
Content-Type: application/json

###

# Get post by title:
GET http://localhost:3000/api/post?title=some HTTP/1.1
Content-Type: application/json

###

# Delete post by ID:
DELETE http://localhost:3000/api/post/978c05ff-fc3a-4f12-99a4-7474d9a34dce HTTP/1.1
Content-Type: application/json

###

# Update post by ID:
PATCH http://localhost:3000/api/post/cd85e2a6-4be0-48da-8669-37019fa47288 HTTP/1.1
Content-Type: application/json

{
  "title": "New amazing title",
  "announcement": "New amazing announcement",
  "text": "New amazing text"
}

###
