# Create post:
POST http://localhost:3000/api/post HTTP/1.1
Content-Type: application/json

{
  "title": "Some title of new tech post",
  "announcement": "Some announcement of new tech post",
  "text": "Some text of new tech post",
  "isReposted": false,
  "commentCount": 0,
  "likeCount": 0,
  "userId": "8231762309c030b503e30915",
  "state": "published",
  "type": "text",
  "tags": ["tech", "new", "post"]
}

###

# Get all posts:
GET http://localhost:3000/api/post/list HTTP/1.1
Content-Type: application/json

###

# Get post by ID:
GET http://localhost:3000/api/post/6d308040-96a2-4162-bea6-2338e9976540 HTTP/1.1
Content-Type: application/json

###

# Get post by title:
GET http://localhost:3000/api/post?title=Some title of new tech post HTTP/1.1
Content-Type: application/json

###

# Delete post by ID:
DELETE http://localhost:3000/api/post/06f13e5f-233e-4603-acf9-1baa5a936040 HTTP/1.1
Content-Type: application/json

###

# Update post by ID:
PATCH http://localhost:3000/api/post/87fbf4c7-2115-41ff-bb50-1d061acc7928 HTTP/1.1
Content-Type: application/json

{
  "title": "New amazing title",
  "announcement": "New amazing announcement",
  "text": "New amazing text",
  "tags": ["digital"]
}

###
