# Create new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound33.local",
  "name": "Alex",
  "password": "123456",
  "avatarPath": "https://i.pravatar.cc/300"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/682376a4d507113c3947fab4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODIzNzZhNGQ1MDcxMTNjMzk0N2ZhYjQiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJuYW1lIjoiQWxleCIsImlhdCI6MTc0ODM3OTMzMiwiZXhwIjoxNzQ4Mzc5NjMyfQ.bNmcGcoah7bDKf5ixGcnXVVm0eOoIDj1HGtduxi_br8

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
