# Create new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "name": "Alex",
  "password": "123456",
  "avatarPath": "https://i.pravatar.cc/300"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/68231b887ab53c01ea50e298 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
