# Create like to post: (disabled in module)
POST http://localhost:3002/api/likes HTTP/1.1
Content-Type: application/json

{
  "postId": "e3bf7830-78a4-4ba7-bfaa-2977f116051b",
  "userId": "658170cbb954e9f5b905ccf4"
}
###

# Delete like from post: (disabled in module)
DELETE http://localhost:3002/api/likes HTTP/1.1
Content-Type: application/json

{
  "postId": "e3bf7830-78a4-4ba7-bfaa-2977f116051b",
  "userId": "658170cbb954e9f5b905ccf4"
}
###
